name: CI/CD Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Backend Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend
        docker push ghcr.io/${{ github.repository_owner }}/backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./frontend
        docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GHCR_TOKEN }}"
          mkdir -p ~/deploy-task3
          cd ~/deploy-task3

          # Optional: Pull latest docker-compose.yml from GitHub
          rm -f docker-compose.yml
          curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml

          docker-compose down
          sudo fuser -k 8091/tcp || true
          sudo fuser -k 3099/tcp || true
          docker-compose pull
          docker-compose up -d
